{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savant-dataplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: savant-dataplane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: agent
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.agent.service.port }}
      targetPort: http
{{- end }}
