{{- if .Values.analyticEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: analytic-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savant-dataplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytic-engine
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: savant-dataplane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: analytic-engine
  ports:
    - name: http-spark
      protocol: TCP
      port: {{ .Values.analyticEngine.service.port }}
      targetPort: http-spark
{{- end }}
