{{- if and .Values.savantConfig.controlPlane.credentialConfig (not .Values.savantConfig.controlPlane.existingCredentialConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gcp-credential-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savant-dataplane.labels" . | nindent 4 }}
data:
  credential-config.json: |
{{ .Values.savantConfig.controlPlane.credentialConfig | indent 4 }}
{{- end }}
