apiVersion: v1
kind: ServiceAccount
metadata:
  name: savant-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savant-dataplane.labels" . | nindent 4 }}
  {{- with .Values.savantConfig.aws.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
