apiVersion: v1
kind: ServiceAccount
metadata:
  name: savant-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "savant-dataplane.labels" . | nindent 4 }}
  {{- if and (eq .Values.savantConfig.cloudProvider "aws") .Values.savantConfig.aws.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.savantConfig.aws.roleArn | quote }}
  {{- end }}
